FROM apache/airflow:2.8.1-python3.11

USER root

# Instalar Java (necesario para PySpark)
RUN apt-get update && \
    apt-get install -y --no-install-recommends openjdk-17-jdk-headless && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="${JAVA_HOME}/bin:${PATH}"

USER airflow

# Instalar providers y PySpark
RUN pip install --no-cache-dir \
    apache-airflow-providers-apache-spark==4.1.5 \
    pyspark==3.5.0