# ─────────────────────────────────────────────────────────────
#  SPARK DEFAULTS — Lago de Datos Federado
#  Imagen: apache/spark:3.5.3-python3
# ─────────────────────────────────────────────────────────────

# Hive Metastore
spark.sql.catalogImplementation             hive
spark.hadoop.hive.metastore.uris            thrift://hive-metastore:9083

# S3A → MinIO unificado (Bronze / Silver / Gold)
spark.hadoop.fs.s3a.endpoint                http://minio:9000
spark.hadoop.fs.s3a.access.key              minioadmin
spark.hadoop.fs.s3a.secret.key              minioadmin123
spark.hadoop.fs.s3a.path.style.access       true
spark.hadoop.fs.s3a.impl                    org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled  false
spark.hadoop.fs.s3a.aws.credentials.provider org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider

# Recursos (ajustado a 8GB WSL2)
spark.driver.memory                         1g
spark.executor.memory                       1g
spark.executor.cores                        1

# Parquet
spark.sql.parquet.compression.codec         snappy